image: ${CI_REGISTRY}/rey/debian-ci:latest

variables:
  SPIGOT_VERSION: "1.13.1"

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - java -version
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - java -jar BuildTools.jar --rev ${SPIGOT_VERSION}
    - mv spigot-${SPIGOT_VERSION}.jar spigot.jar
    - mv craftbukkit-${SPIGOT_VERSION}.jar craftbukkit.jar
  artifacts:
    paths:
    - spigot.jar
    - craftbukkit.jar
