image: ${CI_REGISTRY}/rey/debian-ci/java-ci:latest

stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - java -jar BuildTools.jar --rev 1.13
