image: ${CI_REGISTRY}/rey/debian-ci/java:latest

variables:
  SPIGOT_VERSION: "1.13.2"

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  tags:
    - docker
  script:
    - cd build
    - java -version
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - java -jar BuildTools.jar --rev ${SPIGOT_VERSION}
    - mv spigot-${SPIGOT_VERSION}.jar spigot.jar
    - mv craftbukkit-${SPIGOT_VERSION}.jar craftbukkit.jar
  artifacts:
    paths:
    - build/spigot.jar
    - build/craftbukkit.jar

test:
  stage: test
  tags:
    - docker
  script:
  # We are assuming that the #docker runners have access to a /world volume containing a backup of a test world
    - cp -auf /world build/
    - cd build
    - export LC_CTYPE=en_US.UTF-8
    - /usr/bin/tmux new-session -d -s spigot "java -Xms300M -Xmx300M -XX:+UseConcMarkSweepGC -jar spigot.jar nogui"
    - sleep 60
    - /usr/bin/tmux send-keys -t spigot version Enter
    - sleep 20
    - /usr/bin/tmux capture-pane -pt "$target-pane"
    - /usr/bin/tmux capture-pane -pt "$target-pane" | grep 'Done'
    - /usr/bin/tmux capture-pane -pt "$target-pane" | grep 'You are running the latest version'

deploy:
  stage: deploy
  only:
    - tags
    - schedules
  tags:
    - salt-master
  script:
    - rsync --delete -a --exclude .gitlab-ci.yml --exclude .git . /srv/salt/spigot/
    - sudo /usr/bin/salt mine -t 600 test.ping
    - sudo /usr/bin/salt mine -t 600 state.apply spigot
    - sleep 240
    - sudo /usr/bin/salt mine -t 600 test.ping
    - sudo /usr/bin/salt mine -t 600 cmd.run /usr/local/sbin/spigot-ver | grep -E 'Done|version'
