FROM debian:stretch

# Get certificate material
COPY ca-certificates /usr/local/share/ca-certificates/

# Get OpenJDK and tmux
RUN apt-get -qy update \
    && apt-get -qy install \
      git \
      locales \
      openjdk-8-jre-headless=8u171-b11-1~deb9u1 \
      tmux \
      wget \
    && echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen \
    && locale-gen \
    && useradd -ms /bin/bash user

USER user
